name: Test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [17, 18]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - run: ./gradlew checkLicenses --stacktrace
      - run: ./gradlew check build --stacktrace
